version: '3'
services:
  node:
    build: ./friend-management
    ports:
    - "3000:3000"
    links:
    - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      'bash -c "mongoimport --host mongodb --db user --collection users --type json --file /mongo-seed/user.json --jsonArray"'